// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: proto/roomdata.proto

package wcferry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members      []*RoomData_RoomMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Field_2      int32                  `protobuf:"varint,2,opt,name=field_2,json=field2,proto3" json:"field_2,omitempty"`
	Field_3      int32                  `protobuf:"varint,3,opt,name=field_3,json=field3,proto3" json:"field_3,omitempty"`
	Field_4      int32                  `protobuf:"varint,4,opt,name=field_4,json=field4,proto3" json:"field_4,omitempty"`
	RoomCapacity int32                  `protobuf:"varint,5,opt,name=room_capacity,json=roomCapacity,proto3" json:"room_capacity,omitempty"`
	Field_6      int32                  `protobuf:"varint,6,opt,name=field_6,json=field6,proto3" json:"field_6,omitempty"`
	Field_7      int64                  `protobuf:"varint,7,opt,name=field_7,json=field7,proto3" json:"field_7,omitempty"`
	Field_8      int64                  `protobuf:"varint,8,opt,name=field_8,json=field8,proto3" json:"field_8,omitempty"`
}

func (x *RoomData) Reset() {
	*x = RoomData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_roomdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomData) ProtoMessage() {}

func (x *RoomData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roomdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomData.ProtoReflect.Descriptor instead.
func (*RoomData) Descriptor() ([]byte, []int) {
	return file_proto_roomdata_proto_rawDescGZIP(), []int{0}
}

func (x *RoomData) GetMembers() []*RoomData_RoomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RoomData) GetField_2() int32 {
	if x != nil {
		return x.Field_2
	}
	return 0
}

func (x *RoomData) GetField_3() int32 {
	if x != nil {
		return x.Field_3
	}
	return 0
}

func (x *RoomData) GetField_4() int32 {
	if x != nil {
		return x.Field_4
	}
	return 0
}

func (x *RoomData) GetRoomCapacity() int32 {
	if x != nil {
		return x.RoomCapacity
	}
	return 0
}

func (x *RoomData) GetField_6() int32 {
	if x != nil {
		return x.Field_6
	}
	return 0
}

func (x *RoomData) GetField_7() int64 {
	if x != nil {
		return x.Field_7
	}
	return 0
}

func (x *RoomData) GetField_8() int64 {
	if x != nil {
		return x.Field_8
	}
	return 0
}

type RoomData_RoomMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wxid  string `protobuf:"bytes,1,opt,name=wxid,proto3" json:"wxid,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State int32  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *RoomData_RoomMember) Reset() {
	*x = RoomData_RoomMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_roomdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomData_RoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomData_RoomMember) ProtoMessage() {}

func (x *RoomData_RoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_roomdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomData_RoomMember.ProtoReflect.Descriptor instead.
func (*RoomData_RoomMember) Descriptor() ([]byte, []int) {
	return file_proto_roomdata_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RoomData_RoomMember) GetWxid() string {
	if x != nil {
		return x.Wxid
	}
	return ""
}

func (x *RoomData_RoomMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomData_RoomMember) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_proto_roomdata_proto protoreflect.FileDescriptor

var file_proto_roomdata_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x77, 0x63, 0x66, 0x65, 0x72, 0x72, 0x79, 0x22,
	0xd1, 0x02, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x77, 0x63, 0x66, 0x65, 0x72, 0x72, 0x79, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x12, 0x17, 0x0a,
	0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x33, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x34, 0x12,
	0x23, 0x0a, 0x0d, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x61, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x36, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x36, 0x12, 0x1b, 0x0a,
	0x07, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x37, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x42, 0x02,
	0x30, 0x01, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x37, 0x12, 0x1b, 0x0a, 0x07, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x38, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x42, 0x02, 0x30, 0x01, 0x52,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x38, 0x1a, 0x4a, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x78, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x78, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x77, 0x63, 0x66, 0x65, 0x72, 0x72,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_roomdata_proto_rawDescOnce sync.Once
	file_proto_roomdata_proto_rawDescData = file_proto_roomdata_proto_rawDesc
)

func file_proto_roomdata_proto_rawDescGZIP() []byte {
	file_proto_roomdata_proto_rawDescOnce.Do(func() {
		file_proto_roomdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_roomdata_proto_rawDescData)
	})
	return file_proto_roomdata_proto_rawDescData
}

var file_proto_roomdata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_roomdata_proto_goTypes = []interface{}{
	(*RoomData)(nil),            // 0: wcferry.RoomData
	(*RoomData_RoomMember)(nil), // 1: wcferry.RoomData.RoomMember
}
var file_proto_roomdata_proto_depIdxs = []int32{
	1, // 0: wcferry.RoomData.members:type_name -> wcferry.RoomData.RoomMember
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_roomdata_proto_init() }
func file_proto_roomdata_proto_init() {
	if File_proto_roomdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_roomdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_roomdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomData_RoomMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_roomdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_roomdata_proto_goTypes,
		DependencyIndexes: file_proto_roomdata_proto_depIdxs,
		MessageInfos:      file_proto_roomdata_proto_msgTypes,
	}.Build()
	File_proto_roomdata_proto = out.File
	file_proto_roomdata_proto_rawDesc = nil
	file_proto_roomdata_proto_goTypes = nil
	file_proto_roomdata_proto_depIdxs = nil
}
