#!/bin/sh
#

PATH=.:$PATH

cd /srv

yml=${1:-config.yml}

if [ !-f $yml ]; then
    cp -av config.yml $yml
fi

sed -i "s/192.168.1.2:7601/$WCF_ADDRESS/" $yml
sed -i "/SdkLibrary:/d" $yml

exec wrest $yml
